export const refs = {
  categoriesElem: document.querySelector('.categories'),
  productsElem: document.querySelector('.products'),
  loadMoreElem: document.querySelector('.load-more-btn'),
  modalElem: document.querySelector('.modal-product'),
  modalRoot: document.querySelector('.modal'),
  modalCloseElem: document.querySelector('.modal__close-btn'),
  formElem: document.querySelector('.search-form'),
  inputElem: document.querySelector('.search-form__input'),
  themeElem: document.querySelector('.theme-toggle-btn'),
  cartNumElem: document.querySelector('.js-cart-count'),
  wishNumElem: document.querySelector('.js-wish-count'),
  cartProducts: document.querySelector('.js-cart-products'),
  wishProducts: document.querySelector('.js-wish-products'),
};
